"""initial migration (bets)

Revision ID: 13a024882f91
Revises: 
Create Date: 2024-12-10 14:49:57.965009

"""

from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "13a024882f91"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bet",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("number", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("coefficient", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("deadline", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("Unfinished", "First_win", "Second_win", name="eventstatus"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("number"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bet")
    op.execute("DROP TYPE IF EXISTS eventstatus")
    # ### end Alembic commands ###
