"""made event deadline bigint

Revision ID: 61e7e0ec6bce
Revises: 534d33ce6db6
Create Date: 2024-12-12 19:44:01.196734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61e7e0ec6bce'
down_revision: Union[str, None] = '534d33ce6db6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'deadline',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'deadline',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
